#
# # Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- block:
    - name: Initiate postgres
      become: yes
      shell: "{{ postgres_initdb_command }}"
      args:
        creates: "{{ postgres_hba_file }}"

    - name: Configure postgres to listen on all interfaces
      lineinfile:
        path: "{{ postgres_config_file }}"
        line: "listen_addresses = '*'"
        regexp: '^#?listen_addresses\s+='
        state: present
      notify: Restart postgres

    - name: Set postgres max_connections
      lineinfile:
        path: "{{ postgres_config_file }}"
        line: "max_connections = {{ postgres_max_connections }}"
        regexp: '^#?max_connections\s+='
        state: present
      notify: Restart postgres

    - name: Configure access for the database without ident auth)
      lineinfile:
        path: "{{ postgres_hba_file }}"
        line: "host all all 127.0.0.1/32 md5"
        regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+ident\s+.*'
        insertbefore: EOF
        state: present
      notify: Restart postgres
  when: database == "postgres"

- name: Configure mysql
  include_tasks: mysql-setup.yml
  when: database == "mysql" or database == "mariadb"

- name: Make sure the "{{ database }}" service is started
  service:
    name: "{{ hostvars[inventory_hostname][database + '_service_name'] }}"
    state: started

- name: Make sure the "{{ database }}" service is enabled
  service:
    name: "{{ hostvars[inventory_hostname][database + '_service_name'] }}"
    enabled: yes
  ignore_errors: true

- meta: flush_handlers

- name: Prepare the ambari database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.ambari_db_name }}"
    db_username: "{{ database_options.ambari_db_username }}"
    db_password: "{{ database_options.ambari_db_password }}"


- name: Prepare the hive database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.hive_db_name }}"
    db_username: "{{ database_options.hive_db_username }}"
    db_password: "{{ database_options.hive_db_password }}"

- name: Prepare the dolphin database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.dolphin_db_name }}"
    db_username: "{{ database_options.dolphin_db_username }}"
    db_password: "{{ database_options.dolphin_db_password }}"


- name: Prepare the superset database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.superset_db_name }}"
    db_username: "{{ database_options.superset_db_username }}"
    db_password: "{{ database_options.superset_db_password }}"

- name: Prepare the cloudbeaver database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.cloudbeaver_db_name }}"
    db_username: "{{ database_options.cloudbeaver_db_username }}"
    db_password: "{{ database_options.cloudbeaver_db_password }}"


- name: Prepare the nightingale database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.nightingale_db_name }}"
    db_username: "{{ database_options.nightingale_db_username }}"
    db_password: "{{ database_options.nightingale_db_password }}"


- name: Prepare the ranger database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.rangeradmin_db_name }}"
    db_username: "{{ database_options.rangeradmin_db_username }}"
    db_password: "{{ database_options.rangeradmin_db_password }}"


- name: Prepare the rangerkms database
  include_tasks: "{{ database | regex_replace('mariadb', 'mysql') }}_play.yml"
  vars:
    db_name: "{{ database_options.rangerkms_db_name }}"
    db_username: "{{ database_options.rangerkms_db_username }}"
    db_password: "{{ database_options.rangerkms_db_password }}"

